[MSHARED-1290] Fix PropertyUtils cycle detection results in false positives
apache/maven-filtering pull request #78
Opened 2023-07-21 16:40 UTC by wborn

This fixes MSHARED-1290 which was caused by https://github.com/apache/maven-shared/pull/17.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

2023-10-22 13:02 UTC, elharo reviewed
Can the tests be written without inspecting the logger? Logger messages are often side effects that change a lot and shouldn't break unrelated tests

2023-10-22 13:02 UTC, elharo commented on src/test/java/org/apache/maven/shared/filtering/PropertyUtilsTest.java
> +        try (FileWriter writer = new FileWriter(basicProp)) {
try to avoid assuming the default character encoding; e.g. by using an OutputStreamWriter directly inztead

2023-10-22 13:27 UTC, wborn commented
Thanks for having a look! I've addressed your review comments in the new commit @elharo.

2023-10-22 14:16 UTC, elharo requested changes

2023-10-22 14:16 UTC, elharo commented on src/test/java/org/apache/maven/shared/filtering/PropertyUtilsTest.java
> +        File basicProp = new File(testDirectory, "non-circular.properties");
use File.createTempFile and delete it in a finally block

2023-10-23 11:12 UTC, elharo commented on src/test/java/org/apache/maven/shared/filtering/PropertyUtilsTest.java
> +            Properties prop = PropertyUtils.loadPropertyFile(basicProp, false, false, logger);
prop --> properties

2023-10-23 11:12 UTC, elharo commented on src/test/java/org/apache/maven/shared/filtering/PropertyUtilsTest.java
> +            assertTrue(prop.getProperty("key").equals("gani_man"));
assertEquals

2023-10-23 11:12 UTC, elharo commented on src/test/java/org/apache/maven/shared/filtering/PropertyUtilsTest.java
> +            Properties prop = PropertyUtils.loadPropertyFile(systemProp, false, true, logger);
properties

2023-10-23 11:12 UTC, elharo commented on src/test/java/org/apache/maven/shared/filtering/PropertyUtilsTest.java
> +            assertTrue(prop.getProperty("key").equals(System.getProperty("user.dir")));
assertEquals

2023-10-23 11:12 UTC, elharo commented on src/test/java/org/apache/maven/shared/filtering/PropertyUtilsTest.java
> +        } finally {
perhaps just set deleteOnExit instead to avoid IOExceptions here failing the test

2023-12-08 13:38 UTC, elharo approved these changes

2023-12-08 13:38 UTC, merged

2025-06-17 15:32 UTC, jira-importer commented
Resolve #273